# Set up and run GMS

tasks:
  - name: install requirements
    init: pip install -r requirements.txt
  - name: Create .env
    init: |
      cp .env.sample .env
  - name: Start Django Server
    env:
      DJANGO_SETTINGS_MODULE: webapp.settings.dev
    command: |
      cd webapp
      python manage.py migrate
      python manage.py runserver
