# Test this locally with:
# http://127.0.0.1:8000/lab/export?content_root=http://localhost:8000/static/home/labs/proteomics/base.yml

# Request this on site.usegalaxy.org.au with:
# https://site.usegalaxy.org.au/lab/export?content_root=https://site.usegalaxy.org.au/static/home/labs/proteomics/base.yml

# Check out the documentation for building exported labs:
# https://site.usegalaxy.org.au/lab/export

# Use these variables in HTML templates like:
# "Welcome to the Galaxy {{ site_name }} {{ lab_name }}"
# To make the content more generic and reusable across sites
site_name: Australia
lab_name: Proteomics Lab
nationality: Australian
galaxy_base_url: https://proteomics.usegalaxy.org.au  # Use for rendering tool/workflow URLs. Trailing '/' will be removed.
subdomain: proteomics
root_domain: usegalaxy.org.au
feedback_email: help@genome.edu.au

# Custom content relative to this file URL
header_logo: static/logo.png
custom_css: static/custom.css
intro_md: templates/intro.html
conclusion_md: templates/conclusion.html
footer_md: templates/footer.html

# Data (Tools, Workflows etc.) to be rendered into sections/tabs/accordion elements.
# Either:
#   1. Relative to this file URL
#   2. Full URL to fetch globally centralized content
sections:
  - sections/data.yml
  - sections/conversion_modification.yml
  - sections/database_searching.yml
  - sections/dda_standardised_tools.yml
  - sections/dia_standardised_tools.yml
  - sections/dda_tmt.yml
