---

- name: create server directory
  file:
    path: "{{ server_root }}"
    state: directory

- name: Add the deadsnakes PPA repository
  apt_repository:
    repo: ppa:deadsnakes/ppa
    state: present

- name: update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: install systems dependencies
  ansible.builtin.package:
    name:
      - gcc
      - python3.12
      - python3.12-pip
      - python3.12-venv
      - python3.12-dev
      - python3-certbot-nginx

- name: clone git repository for galaxy-content-site
  ansible.builtin.git:
    repo: https://github.com/neoformit/galaxy-content-site.git
    dest: "{{ project_root }}"
    clone: yes
    force: yes

- name: link webapp to /srv/sites
  ansible.builtin.file:
    src: "{{ project_root }}/webapp"
    dest: "{{ web_root }}"
    state: link

- name: create webapp media directory
  file:
    path: "{{ web_root }}/webapp/media"
    state: directory

- name: create webapp logs directory
  file:
    path: "{{ web_root }}/webapp/logs"
    state: directory

- name: template webserver configuration
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop: "{{ webapp.templates }}"

- name: copy webserver configuration
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop: "{{ webapp.files }}"

- name: link to enable nginx virtualhost
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ inventory_hostname }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ inventory_hostname }}"
    state: link

- name: Install Python requirements into venv
  pip:
    requirements: "{{ project_root }}/requirements.txt"
    virtualenv: "{{ venv_root }}"
    virtualenv_python: python3.12

- name: run webapp setup script
  command: "bash {{ server_root }}/setup.sh"

- name: create and install SSL certificate with letsencrypt
  command: "certbot --nginx --noninteractive --agree-tos --redirect --email {{ certbot_renew_email }} -d {{ inventory_hostname }}"
  when: certbot_ssl

- name: Ensure webapp superuser login
  shell: |
    cd {{ web_root }} && \
    export DJANGO_SUPERUSER_PASSWORD={{ admin_user.password }} && \
    {{ venv_root }}/bin/python manage.py createsuperuser --noinput \
      --email {{ admin_user.email }} \
      --first_name {{ admin_user.first_name }} \
      --last_name {{ admin_user.last_name }}
  ignore_errors: yes
  when: admin_user and not skip_database_migration

- name: update project ownership
  ansible.builtin.file:
    path: /home/ubuntu
    state: directory
    recurse: yes
    owner: ubuntu
    group: ubuntu

- name: update media file ownership
  file: dest={{ web_root }}/webapp/media owner=www-data group=www-data mode=u=rwX,g=rwX,o=rwX recurse=yes

- name: update log file ownership
  file: dest={{ web_root }}/webapp/logs owner=www-data group=www-data mode=u=rwX,g=rwX,o=rwX recurse=yes

- name: make update.sh executable
  file: dest=/home/ubuntu/update.sh mode=a+x

- name: check whether news scraper in GMS version
  ansible.builtin.shell: "{{ venv_root }}/bin/python manage.py scrape_news --help"
  args:
    chdir: "{{ web_root }}"
  register: check_scraper

- name: add cron job to scrape news feed
  ansible.builtin.cron:
    name: "scrape news feed"
    user: ubuntu
    hour: 9
    minute: 0
    job: "cd {{ web_root }} && {{ venv_root }}/bin/python manage.py scrape_news"
  when: check_scraper.rc == 0
